services:
  apache_sut:
    build: ./apache-server
    ports:
      # [Localhost Port] : [Container Port (set up in Dockerfile)]
      - "9000:80" # standard port 80 web traffic
    cpuset: "${APACHE_CPU_SET:-0}" # CPU core count depends on bash script (to promote automation), default core 0 if cant read

  node_sut:
    build: ./node-server
    ports:
      # [Localhost Port] : [Container Port (set up in Dockerfile)]
      - "7000:3000"
    cpuset: "${NODE_CPU_SET:-12}" # CPU core count depends on bash script (to promote automation), default core 12 if cant read